import { format } from "prettier";
/** Registry entries name a generated file and an explicit Foundry artifact. */
export async function generateBindings(
  registry: unknown,
  readArtifact: (path: string, source?: "v2") => Promise<unknown>,
): Promise<Map<string, string>> {
  if (!Array.isArray(registry)) throw new Error("Contract registry must be an array");
  const output = new Map<string, string>();
  const identifiers = new Set<string>();
  for (const value of registry) {
    if (value === null || typeof value !== "object")
      throw new Error("Invalid contract registry entry");
    const entry = value as Record<string, unknown>;
    if (
      !["artifact,name", "artifact,name,source"].includes(Object.keys(entry).sort().join(",")) ||
      (entry.source !== undefined && entry.source !== "v2") ||
      typeof entry.name !== "string" ||
      !/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(entry.name) ||
      typeof entry.artifact !== "string" ||
      !/^[a-zA-Z0-9_.-]+\.sol\/[a-zA-Z0-9_-]+\.json$/.test(entry.artifact)
    )
      throw new Error("Invalid contract name or artifact path");
    const file = `${entry.name}.ts`;
    if (entry.name === "index") throw new Error("Reserved contract name");
    if (output.has(file)) throw new Error("Duplicate contract name");
    const artifact = await readArtifact(entry.artifact, entry.source as "v2" | undefined);
    if (
      artifact === null ||
      typeof artifact !== "object" ||
      !("abi" in artifact) ||
      !Array.isArray(artifact.abi) ||
      artifact.abi.length === 0
    )
      throw new Error("Contract artifact has no ABI");
    const identifier =
      entry.name.replace(/-([a-z0-9])/g, (_, letter: string) => letter.toUpperCase()) + "Abi";
    if (identifiers.has(identifier)) throw new Error("Colliding ABI export identifier");
    identifiers.add(identifier);
    output.set(
      file,
      `// Generated by npm run codegen. Do not edit.\nexport const ${identifier} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
    );
  }
  output.set(
    "index.ts",
    "// Generated by npm run codegen. Do not edit.\n" +
      (output.size
        ? [...output.keys()].map((name) => `export * from "./${name.slice(0, -3)}";\n`).join("")
        : "// No Hedge protocol contracts have been implemented yet.\nexport {};\n"),
  );
  for (const [name, content] of output)
    output.set(name, await format(content, { parser: "typescript", printWidth: 100 }));
  return output;
}
